name: Format & Lint Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    name: Format & Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: 1.9.4

      - name: Run Biome
        run: biome ci
